# Generated by Django 5.2.8 on 2026-02-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemas', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('executor', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=120)),
                ('budget_mmbs', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='structure.category')),
                ('entities', models.ManyToManyField(blank=True, help_text='Entidades operativas asociadas al proyecto.', related_name='projects', to='structure.entity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Reporte de proyecto', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curve_executed_dataset', models.ForeignKey(help_text='Esquema con la curva ejecutada (semanal o mensual).', on_delete=django.db.models.deletion.PROTECT, related_name='project_curve_executed_configs', to='schemas.datasettype')),
                ('curve_program_dataset', models.ForeignKey(help_text='Esquema con la curva programada (carga unica).', on_delete=django.db.models.deletion.PROTECT, related_name='project_curve_program_configs', to='schemas.datasettype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to='projects.project')),
                ('report_dataset', models.ForeignKey(help_text='Esquema principal para los datos del reporte.', on_delete=django.db.models.deletion.PROTECT, related_name='project_report_configs', to='schemas.datasettype')),
            ],
            options={
                'ordering': ['project__name', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
