# Generated by Django 5.2.8 on 2026-02-02 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectreportconfig",
            name="curve_executed_dataset",
            field=models.ForeignKey(
                help_text="Esquema con la curva ejecutada (semanal o mensual).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_curve_executed_configs",
                to="schemas.datasettype",
            ),
        ),
        migrations.AddField(
            model_name="projectreportconfig",
            name="curve_program_dataset",
            field=models.ForeignKey(
                help_text="Esquema con la curva programada (carga unica).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_curve_program_configs",
                to="schemas.datasettype",
            ),
        ),
        migrations.AddField(
            model_name="projectreportconfig",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_configs",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectreportconfig",
            name="report_dataset",
            field=models.ForeignKey(
                help_text="Esquema principal para los datos del reporte.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_report_configs",
                to="schemas.datasettype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectreportconfig",
            unique_together={("project", "name")},
        ),
    ]
