# Generated by Django 5.2.7 on 2026-01-15 20:02

from django.db import migrations, models


def copy_project_plant_to_plants(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.exclude(plant__isnull=True):
        project.plants.add(project.plant)


def copy_plants_to_project_plant(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        first = project.plants.first()
        if first:
            project.plant = first
            project.save(update_fields=["plant"])


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="plants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Plantas o unidades operativas asociadas al proyecto.",
                related_name="projects",
                to="plants.plant",
            ),
        ),
        migrations.RunPython(copy_project_plant_to_plants, copy_plants_to_project_plant),
        migrations.RemoveField(
            model_name="project",
            name="plant",
        ),
    ]
