# Generated by Django 5.2.8 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_migrate_project_plants_to_entities"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectreportconfig",
            name="report_variant",
            field=models.CharField(
                default="auto",
                help_text=(
                    "Variante del visor. Use 'auto' para deteccion automatica o un slug "
                    "explicito como 'project', 'agreement' u otra variante futura."
                ),
                max_length=50,
            ),
        ),
    ]
