# Generated by Django 5.2.8 on 2026-03-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_projects_as_approved(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Project.objects.all().update(
        workflow_status="APPROVED",
        is_active=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_projectreportconfig_report_variant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="workflow_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de aprobacion"),
                    ("APPROVED", "Aprobado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            mark_existing_projects_as_approved,
            migrations.RunPython.noop,
        ),
    ]
