# Generated by Django 5.2.8 on 2026-03-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_repair_project_entities_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("PENDING", "Pendiente de aprobacion"),
                    ("APPROVED", "Aprobado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
