# Generated by Django 5.2.8 on 2025-11-24 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("ingest", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Nivel de validación (1, 2, 3...)."
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVE", "Aprobar"), ("REJECT", "Rechazar")],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_actions",
                        to="ingest.datasetinstance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_validation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Membresía del validador que tomó la acción.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_actions",
                        to="accounts.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
