# Generated by Django 5.2.8 on 2025-11-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("plants", "0001_initial"),
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        help_text="Fecha o día de referencia del dataset (para diarios)."
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("SUBMITTED", "Enviado"),
                            ("VALIDATED_L1", "Validado nivel 1"),
                            ("VALIDATED_L2", "Validado nivel 2"),
                            ("PUBLISHED", "Publicado"),
                            ("LOCKED", "Bloqueado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "raw_file",
                    models.FileField(
                        blank=True,
                        help_text="Archivo fuente cargado (CSV/Excel).",
                        null=True,
                        upload_to="ingest/raw/",
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("last_error_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_instances",
                        to="accounts.membership",
                    ),
                ),
                (
                    "dataset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="schemas.datasettype",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_instances",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("dataset_type", "plant", "period")},
            },
        ),
    ]
