# Generated by Django 5.2.8 on 2026-02-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schemas', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('target_period', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_change_requests', to='accounts.membership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetChangeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ingest/change_support/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ingest.datasetchangerequest')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Fecha o día de referencia del dataset (para diarios).')),
                ('state', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviado'), ('VALIDATED_L1', 'Validado nivel 1'), ('VALIDATED_L2', 'Validado nivel 2'), ('PUBLISHED', 'Publicado'), ('LOCKED', 'Bloqueado')], default='DRAFT', max_length=20)),
                ('raw_file', models.FileField(blank=True, help_text='Archivo fuente cargado (CSV/Excel).', null=True, upload_to='ingest/raw/')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_error_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_instances', to='accounts.membership')),
                ('dataset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='schemas.datasettype')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_instances', to='structure.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasetchangerequest',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='ingest.datasetinstance'),
        ),
        migrations.AddField(
            model_name='datasetchangerequest',
            name='target_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_change_requests', to='ingest.datasetinstance'),
        ),
        migrations.CreateModel(
            name='HistoricalImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(blank=True, help_text='Archivo original usado para cargar el histórico.', null=True, upload_to='ingest/historical/')),
                ('date_column_name', models.CharField(help_text='Nombre del encabezado que contiene la fecha por fila.', max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', 'En proceso'), ('DONE', 'Completado'), ('FAILED', 'Fallido')], default='RUNNING', max_length=20)),
                ('error_summary', models.TextField(blank=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('created_instances', models.PositiveIntegerField(default=0)),
                ('updated_instances', models.PositiveIntegerField(default=0)),
                ('skipped_instances', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_imports', to='accounts.membership')),
                ('dataset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_imports', to='schemas.datasettype')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_imports', to='structure.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasetinstance',
            name='historical_batch',
            field=models.ForeignKey(blank=True, help_text='Batch de importación histórica que generó esta instancia (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='ingest.historicalimportbatch'),
        ),
        migrations.CreateModel(
            name='PublishedDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(help_text='Índice de fila dentro del archivo original (comenzando en 1).')),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_points', to='schemas.columndef')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_points', to='ingest.datasetinstance')),
            ],
            options={
                'ordering': ['instance', 'row_index', 'column'],
            },
        ),
        migrations.AddConstraint(
            model_name='datasetinstance',
            constraint=models.UniqueConstraint(fields=('dataset_type', 'entity', 'period'), name='uniq_instance_dataset_entity_period'),
        ),
        migrations.AddIndex(
            model_name='publisheddatapoint',
            index=models.Index(fields=['instance', 'column'], name='ingest_publ_instanc_2e9e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='publisheddatapoint',
            index=models.Index(fields=['column'], name='ingest_publ_column__5b97d1_idx'),
        ),
    ]
