# Generated by Django 5.2.8 on 2025-11-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0001_initial"),
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_index",
                    models.PositiveIntegerField(
                        help_text="Índice de fila dentro del archivo original (comenzando en 1)."
                    ),
                ),
                ("numeric_value", models.FloatField(blank=True, null=True)),
                ("text_value", models.TextField(blank=True)),
                ("date_value", models.DateField(blank=True, null=True)),
                ("bool_value", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_points",
                        to="schemas.columndef",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_points",
                        to="ingest.datasetinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["instance", "row_index", "column"],
                "indexes": [
                    models.Index(
                        fields=["instance", "column"],
                        name="ingest_publ_instanc_2e9e2d_idx",
                    ),
                    models.Index(
                        fields=["column"], name="ingest_publ_column__5b97d1_idx"
                    ),
                ],
            },
        ),
    ]
