# Generated by Django 5.2.8 on 2025-11-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetinstance",
            name="state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("SUBMITTED", "Enviado"),
                    ("VALIDATED_L1", "Validado nivel 1"),
                    ("VALIDATED_L2", "Validado nivel 2"),
                    ("PUBLISHED", "Publicado"),
                    ("LOCKED", "Bloqueado"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
