# Generated by Django 5.2.7 on 2025-12-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("ingest", "0001_initial"),
        ("plants", "0001_initial"),
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        help_text="Archivo original usado para cargar el histórico.",
                        null=True,
                        upload_to="ingest/historical/",
                    ),
                ),
                (
                    "date_column_name",
                    models.CharField(
                        help_text="Nombre del encabezado que contiene la fecha por fila.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "En proceso"),
                            ("DONE", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("error_summary", models.TextField(blank=True)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("total_days", models.PositiveIntegerField(default=0)),
                ("created_instances", models.PositiveIntegerField(default=0)),
                ("updated_instances", models.PositiveIntegerField(default=0)),
                ("skipped_instances", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historical_imports",
                        to="accounts.membership",
                    ),
                ),
                (
                    "dataset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_imports",
                        to="schemas.datasettype",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_imports",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
