# Generated by Django 5.2.8 on 2026-02-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_initial"),
        ("ingest", "0001_initial"),
        ("plants", "0001_initial"),
        ("projects", "0001_initial"),
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetinstance",
            name="dataset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="schemas.datasettype",
            ),
        ),
        migrations.AddField(
            model_name="datasetinstance",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_instances",
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="datasetinstance",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_instances",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="datasetchangerequest",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_requests",
                to="ingest.datasetinstance",
            ),
        ),
        migrations.AddField(
            model_name="datasetchangerequest",
            name="target_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_change_requests",
                to="ingest.datasetinstance",
            ),
        ),
        migrations.AddField(
            model_name="historicalimportbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historical_imports",
                to="accounts.membership",
            ),
        ),
        migrations.AddField(
            model_name="historicalimportbatch",
            name="dataset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historical_imports",
                to="schemas.datasettype",
            ),
        ),
        migrations.AddField(
            model_name="historicalimportbatch",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historical_imports",
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="datasetinstance",
            name="historical_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Batch de importación histórica que generó esta instancia (si aplica).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="ingest.historicalimportbatch",
            ),
        ),
        migrations.AddField(
            model_name="publisheddatapoint",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_points",
                to="schemas.columndef",
            ),
        ),
        migrations.AddField(
            model_name="publisheddatapoint",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_points",
                to="ingest.datasetinstance",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasetinstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plant__isnull", False)),
                fields=("dataset_type", "plant", "period"),
                name="uniq_instance_dataset_plant_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasetinstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("dataset_type", "project", "period"),
                name="uniq_instance_dataset_project_period",
            ),
        ),
        migrations.AddIndex(
            model_name="publisheddatapoint",
            index=models.Index(
                fields=["instance", "column"], name="ingest_publ_instanc_2e9e2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publisheddatapoint",
            index=models.Index(
                fields=["column"], name="ingest_publ_column__5b97d1_idx"
            ),
        ),
    ]
