# Generated by Django 5.2.7 on 2025-12-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0002_historicalimportbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetinstance",
            name="historical_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Batch de importación histórica que generó esta instancia (si aplica).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="ingest.historicalimportbatch",
            ),
        ),
        migrations.AddField(
            model_name="historicalimportbatch",
            name="period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalimportbatch",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
