# Generated by Django 5.2.7 on 2025-12-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0003_datasetchangerequest_datasetchangeattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetchangerequest",
            name="target_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_change_requests",
                to="ingest.datasetinstance",
            ),
        ),
        migrations.AddField(
            model_name="datasetchangerequest",
            name="target_period",
            field=models.DateField(blank=True, null=True),
        ),
    ]
