# Generated by Django 5.2.7 on 2026-01-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0003_datasetinstance_historical_batch_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="datasetinstance",
            unique_together=set(),
        ),
    ]
