# Generated by Django 5.2.7 on 2026-01-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_membership_project_and_more"),
        ("ingest", "0004_alter_datasetinstance_unique_together"),
        ("plants", "0001_initial"),
        ("projects", "0001_initial"),
        ("schemas", "0004_alter_datasettype_validation_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetinstance",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_instances",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="datasetinstance",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_instances",
                to="plants.plant",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasetinstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plant__isnull", False)),
                fields=("dataset_type", "plant", "period"),
                name="uniq_instance_dataset_plant_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasetinstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("dataset_type", "project", "period"),
                name="uniq_instance_dataset_project_period",
            ),
        ),
    ]
