# Generated by Django 5.2.7 on 2025-12-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0004_datasetchangerequest_target_instance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetinstance",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
