# Generated by Django 5.2.8 on 2026-02-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schemas", "0001_initial"),
        ("structure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceVariable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.SlugField(
                        help_text="Llave estable (ej: pcs.brine_volume_m3, kcl.feed_mass_tm).",
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("NUMBER", "Numerico"),
                            ("TEXT", "Texto"),
                            ("DATE", "Fecha"),
                            ("BOOLEAN", "Booleano"),
                        ],
                        default="NUMBER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_variables",
                        to="structure.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["entity__code", "key"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceIndicator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.SlugField(
                        help_text="Llave estable del indicador (ej: pcs.yield_monthly_pct).",
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "formula_text",
                    models.TextField(
                        blank=True,
                        help_text="Descripcion textual de la formula (referencial, para auditoria).",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diario"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensual"),
                            ("YEARLY", "Anual"),
                        ],
                        default="MONTHLY",
                        help_text="Frecuencia por defecto para evaluar esta formula.",
                        max_length=20,
                    ),
                ),
                (
                    "expression",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Expresion (tokens) configurada desde el constructor visual.",
                    ),
                ),
                (
                    "expression_text",
                    models.TextField(
                        blank=True,
                        help_text="Expresion legible para el usuario (generada desde el builder).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_indicators",
                        to="structure.entity",
                    ),
                ),
                (
                    "variables",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Variables metodologicas requeridas.",
                        related_name="indicators",
                        to="performance.performancevariable",
                    ),
                ),
            ],
            options={
                "ordering": ["entity__code", "key"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceIndicatorInput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "token",
                    models.SlugField(
                        help_text="Identificador usado dentro de la formula (ej: v1, var_kcl).",
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("SUM", "Suma"),
                            ("AVG", "Promedio"),
                            ("MAX", "Maximo"),
                            ("MIN", "Minimo"),
                            ("LAST", "Ultimo (por periodo)"),
                            ("NONE", "Sin agregacion"),
                        ],
                        default="SUM",
                        max_length=10,
                    ),
                ),
                (
                    "transform",
                    models.CharField(
                        choices=[
                            ("NONE", "Ninguna"),
                            ("MULTIPLY", "Multiplicar por factor"),
                            ("ADD", "Sumar factor"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("transform_value", models.FloatField(blank=True, null=True)),
                (
                    "offset_periods",
                    models.IntegerField(
                        default=0,
                        help_text="Desfase de periodos segun la frecuencia seleccionada (p. ej. 1 = periodo anterior).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performance_inputs",
                        to="schemas.columndef",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="performance.performanceindicator",
                    ),
                ),
            ],
            options={
                "ordering": ["indicator__entity__code", "indicator__key", "token"],
                "unique_together": {("indicator", "token")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceIndicatorResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diario"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensual"),
                            ("YEARLY", "Anual"),
                        ],
                        default="MONTHLY",
                        help_text="Frecuencia del resultado calculado.",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("CERTIFIED", "Certificado")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Calculado"),
                            ("NOT_CALCULABLE", "No calculable"),
                            ("ERROR", "Error"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("numeric_value", models.FloatField(blank=True, null=True)),
                ("text_value", models.TextField(blank=True)),
                ("trace", models.JSONField(blank=True, default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="performance.performanceindicator",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_results",
                        to="structure.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "entity__code", "indicator__key"],
                "unique_together": {("indicator", "entity", "period_end", "frequency")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceVariableMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("SUM", "Suma"),
                            ("AVG", "Promedio"),
                            ("MAX", "Maximo"),
                            ("MIN", "Minimo"),
                            ("LAST", "Ultimo (por periodo)"),
                            ("NONE", "Sin agregacion"),
                        ],
                        default="SUM",
                        max_length=10,
                    ),
                ),
                (
                    "transform",
                    models.CharField(
                        choices=[
                            ("NONE", "Ninguna"),
                            ("MULTIPLY", "Multiplicar por factor"),
                            ("ADD", "Sumar factor"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("transform_value", models.FloatField(blank=True, null=True)),
                (
                    "offset_months",
                    models.IntegerField(
                        default=0,
                        help_text="Desfase para fuentes mensuales (ej: PCS por lote). m -> m - offset_months.",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("CERTIFIED", "Certificado")],
                        default="DRAFT",
                        help_text="Permite definir mapeos distintos para resultados Draft vs Certificado.",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performance_mappings",
                        to="schemas.columndef",
                    ),
                ),
                (
                    "dataset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performance_mappings",
                        to="schemas.datasettype",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="performance.performancevariable",
                    ),
                ),
            ],
            options={
                "ordering": ["variable__entity__code", "variable__key", "-is_active", "-updated_at"],
                "unique_together": {("variable", "dataset_type", "column", "offset_months", "stage")},
            },
        ),
    ]
