# Generated by Django 5.2.8 on 2026-02-02 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceVariableMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("SUM", "Suma"),
                            ("AVG", "Promedio"),
                            ("MAX", "Máximo"),
                            ("MIN", "Mínimo"),
                            ("LAST", "Último (por periodo)"),
                            ("NONE", "Sin agregación"),
                        ],
                        default="SUM",
                        max_length=10,
                    ),
                ),
                (
                    "transform",
                    models.CharField(
                        choices=[
                            ("NONE", "Ninguna"),
                            ("MULTIPLY", "Multiplicar por factor"),
                            ("ADD", "Sumar factor"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("transform_value", models.FloatField(blank=True, null=True)),
                (
                    "offset_months",
                    models.IntegerField(
                        default=0,
                        help_text="Desfase para fuentes mensuales (ej: PCS por lote). m -> m - offset_months.",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("CERTIFIED", "Certificado")],
                        default="DRAFT",
                        help_text="Permite definir mapeos distintos para resultados Draft vs Certificado.",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "variable__plant__code",
                    "variable__key",
                    "-is_active",
                    "-updated_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Llave estable del indicador (ej: pcs.yield_monthly_pct).",
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "formula_text",
                    models.TextField(
                        blank=True,
                        help_text="Descripción textual de la fórmula (referencial, para auditoría).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_indicators",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["plant__code", "key"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceIndicatorResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[("DAILY", "Diario"), ("MONTHLY", "Mensual")],
                        default="MONTHLY",
                        help_text="Frecuencia del resultado calculado.",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("CERTIFIED", "Certificado")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Calculado"),
                            ("NOT_CALCULABLE", "No calculable"),
                            ("ERROR", "Error"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("numeric_value", models.FloatField(blank=True, null=True)),
                ("text_value", models.TextField(blank=True)),
                ("trace", models.JSONField(blank=True, default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="performance.performanceindicator",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_results",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "plant__code", "indicator__key"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Llave estable (ej: pcs.brine_volume_m3, kcl.feed_mass_tm).",
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("NUMBER", "Numérico"),
                            ("TEXT", "Texto"),
                            ("DATE", "Fecha"),
                            ("BOOLEAN", "Booleano"),
                        ],
                        default="NUMBER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_variables",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["plant__code", "key"],
            },
        ),
        migrations.AddField(
            model_name="performanceindicator",
            name="variables",
            field=models.ManyToManyField(
                blank=True,
                help_text="Variables metodológicas requeridas.",
                related_name="indicators",
                to="performance.performancevariable",
            ),
        ),
    ]
