# Generated by Django 5.2.8 on 2026-02-02 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("performance", "0001_initial"),
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancevariablemapping",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performance_mappings",
                to="schemas.columndef",
            ),
        ),
        migrations.AddField(
            model_name="performancevariablemapping",
            name="dataset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performance_mappings",
                to="schemas.datasettype",
            ),
        ),
        migrations.AddField(
            model_name="performancevariablemapping",
            name="variable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mappings",
                to="performance.performancevariable",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performanceindicatorresult",
            unique_together={("indicator", "plant", "period_end", "frequency")},
        ),
        migrations.AlterUniqueTogether(
            name="performancevariablemapping",
            unique_together={
                ("variable", "dataset_type", "column", "offset_months", "stage")
            },
        ),
    ]
