# Generated by Django 5.2.7 on 2025-12-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceIndicatorResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Calculado"),
                            ("NOT_CALCULABLE", "No calculable"),
                            ("ERROR", "Error"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("numeric_value", models.FloatField(blank=True, null=True)),
                ("text_value", models.TextField(blank=True)),
                ("trace", models.JSONField(blank=True, default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="performance.performanceindicator",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_results",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "plant__code", "indicator__key"],
                "unique_together": {("indicator", "plant", "period_end")},
            },
        ),
    ]
