# Generated by Django 5.2.8 on 2026-02-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("performance", "0001_initial"),
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="performanceindicator",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_indicators",
                to="plants.plant",
            ),
        ),
    ]
