# Generated by Django 5.2.8 on 2026-02-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceindicator',
            name='expression',
            field=models.JSONField(blank=True, default=list, help_text='Expresión (tokens) configurada desde el constructor visual.'),
        ),
        migrations.AlterField(
            model_name='performanceindicator',
            name='expression_text',
            field=models.TextField(blank=True, help_text='Expresión legible para el usuario (generada desde el builder).'),
        ),
        migrations.AlterField(
            model_name='performanceindicator',
            name='formula_text',
            field=models.TextField(blank=True, help_text='Descripción textual de la fórmula (referencial, para auditoría).'),
        ),
        migrations.AlterField(
            model_name='performanceindicator',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('YEARLY', 'Anual')], default='MONTHLY', help_text='Frecuencia por defecto para evaluar esta fórmula.', max_length=20),
        ),
        migrations.AlterField(
            model_name='performanceindicator',
            name='variables',
            field=models.ManyToManyField(blank=True, help_text='Variables metodológicas requeridas.', related_name='indicators', to='performance.performancevariable'),
        ),
        migrations.AlterField(
            model_name='performanceindicatorinput',
            name='aggregation',
            field=models.CharField(choices=[('SUM', 'Suma'), ('AVG', 'Promedio'), ('MAX', 'Máximo'), ('MIN', 'Mínimo'), ('LAST', 'Último (por periodo)'), ('NONE', 'Sin agregación')], default='SUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='performanceindicatorinput',
            name='offset_periods',
            field=models.IntegerField(default=0, help_text='Desfase de periodos según la frecuencia seleccionada (p. ej. 1 = periodo anterior).'),
        ),
        migrations.AlterField(
            model_name='performanceindicatorinput',
            name='token',
            field=models.SlugField(help_text='Identificador usado dentro de la fórmula (ej: v1, var_kcl).', max_length=40),
        ),
        migrations.AlterField(
            model_name='performancevariable',
            name='value_type',
            field=models.CharField(choices=[('NUMBER', 'Numérico'), ('TEXT', 'Texto'), ('DATE', 'Fecha'), ('BOOLEAN', 'Booleano')], default='NUMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='performancevariablemapping',
            name='aggregation',
            field=models.CharField(choices=[('SUM', 'Suma'), ('AVG', 'Promedio'), ('MAX', 'Máximo'), ('MIN', 'Mínimo'), ('LAST', 'Último (por periodo)'), ('NONE', 'Sin agregación')], default='SUM', max_length=10),
        ),
    ]
