# Generated by Django 5.2.8 on 2026-02-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("performance", "0002_initial"),
        ("plants", "0001_initial"),
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="performanceindicatorinput",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performance_inputs",
                to="schemas.columndef",
            ),
        ),
        migrations.AddField(
            model_name="performanceindicatorinput",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inputs",
                to="performance.performanceindicator",
            ),
        ),
        migrations.AddField(
            model_name="performanceindicatorresult",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="performance.performanceindicator",
            ),
        ),
        migrations.AddField(
            model_name="performanceindicatorresult",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_results",
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="performancevariable",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_variables",
                to="plants.plant",
            ),
        ),
        migrations.AddField(
            model_name="performanceindicator",
            name="variables",
            field=models.ManyToManyField(
                blank=True,
                help_text="Variables metodológicas requeridas.",
                related_name="indicators",
                to="performance.performancevariable",
            ),
        ),
        migrations.AddField(
            model_name="performancevariablemapping",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performance_mappings",
                to="schemas.columndef",
            ),
        ),
        migrations.AddField(
            model_name="performancevariablemapping",
            name="dataset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performance_mappings",
                to="schemas.datasettype",
            ),
        ),
        migrations.AddField(
            model_name="performancevariablemapping",
            name="variable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mappings",
                to="performance.performancevariable",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performanceindicatorinput",
            unique_together={("indicator", "token")},
        ),
        migrations.AlterUniqueTogether(
            name="performanceindicatorresult",
            unique_together={("indicator", "plant", "period_end", "frequency")},
        ),
        migrations.AlterUniqueTogether(
            name="performancevariablemapping",
            unique_together={
                ("variable", "dataset_type", "column", "offset_months", "stage")
            },
        ),
    ]
