# Generated by Django 5.2.7 on 2025-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_performanceindicatorresult"),
        ("plants", "0001_initial"),
        ("schemas", "0002_datasettype_source_dataset_last_consolidated_period"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performanceindicatorresult",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="performancevariablemapping",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="performanceindicatorresult",
            name="stage",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("CERTIFIED", "Certificado")],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="performancevariablemapping",
            name="stage",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("CERTIFIED", "Certificado")],
                default="DRAFT",
                help_text="Permite definir mapeos distintos para resultados Draft vs Certificado.",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performanceindicatorresult",
            unique_together={("indicator", "plant", "period_end", "stage")},
        ),
        migrations.AlterUniqueTogether(
            name="performancevariablemapping",
            unique_together={
                ("variable", "dataset_type", "column", "offset_months", "stage")
            },
        ),
    ]
