# Generated by Django 5.2.8 on 2026-02-25 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0003_migrate_plant_columns_to_entity"),
        ("schemas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="performanceindicator",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performanceindicator",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_performance_indicators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="performanceindicator",
            name="output_dataset_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Dataset derivado creado para publicar resultados de esta formula.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_performance_indicators",
                to="schemas.datasettype",
            ),
        ),
        migrations.AddField(
            model_name="performanceindicator",
            name="output_date_column",
            field=models.ForeignKey(
                blank=True,
                help_text="Columna fecha del resultado derivado.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schemas.columndef",
            ),
        ),
        migrations.AddField(
            model_name="performanceindicator",
            name="output_value_column",
            field=models.ForeignKey(
                blank=True,
                help_text="Columna numerica del resultado derivado.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="schemas.columndef",
            ),
        ),
        migrations.AddField(
            model_name="performanceindicator",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("IN_REVIEW", "En revision"),
                    ("APPROVED", "Aprobado"),
                    ("REJECTED", "Rechazado"),
                    ("ARCHIVED", "Archivado"),
                ],
                default="DRAFT",
                help_text="Estado del ciclo de vida de la formula.",
                max_length=20,
            ),
        ),
    ]
