# Generated by Django 5.2.8 on 2026-02-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0003_formula_builder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performanceindicatorresult",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "Diario"),
                    ("WEEKLY", "Semanal"),
                    ("MONTHLY", "Mensual"),
                    ("YEARLY", "Anual"),
                ],
                default="MONTHLY",
                help_text="Frecuencia del resultado calculado.",
                max_length=20,
            ),
        ),
    ]
