# Generated by Django 5.2.8 on 2026-02-10 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccountProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="Si esta activo, el usuario debe cambiar su contrasena antes de usar el sistema.",
                    ),
                ),
                (
                    "last_seen_schema_status",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha/hora en la que el usuario vio por ultima vez el estado de esquemas.",
                        null=True,
                    ),
                ),
                (
                    "last_seen_validation_status",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha/hora en la que el usuario vio por ultima vez el estado de sus cargas.",
                        null=True,
                    ),
                ),
                (
                    "last_seen_certification_alert",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha/hora en la que el usuario revisó las alertas de certificación mensual.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LOADER", "Cargador"),
                            ("VALIDATOR", "Validador"),
                            ("VIEWER", "Visualizador"),
                            ("ADMIN", "Administrador"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "validation_level",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nivel de validacion (1, 2, 3, ...). Solo aplica a validadores.",
                        null=True,
                    ),
                ),
                (
                    "can_validate_daily",
                    models.BooleanField(
                        default=False,
                        help_text="Si es validador, puede participar en el flujo diario.",
                    ),
                ),
                (
                    "can_validate_monthly",
                    models.BooleanField(
                        default=False,
                        help_text="Si es validador, puede participar en el flujo mensual/certificacion.",
                    ),
                ),
                (
                    "can_validate_weekly",
                    models.BooleanField(
                        default=False,
                        help_text="Si es validador, puede participar en el flujo semanal.",
                    ),
                ),
                (
                    "can_validate_projections",
                    models.BooleanField(
                        default=False,
                        help_text="Si es validador, puede participar en el flujo de proyecciones (periodicidad no definida).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Entidad asociada. Vacio solo para roles globales.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="structure.entity",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Institucion a la que pertenece este rol.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="accounts.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("entity__isnull", False)),
                        fields=("user", "entity", "role", "validation_level"),
                        name="uniq_membership_user_entity_role_level",
                    )
                ],
            },
        ),
    ]
