# Generated by Django 5.2.8 on 2025-11-18 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LOADER", "Cargador"),
                            ("VALIDATOR", "Validador"),
                            ("VIEWER", "Visualizador"),
                            ("ADMIN", "Administrador"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "validation_level",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nivel de validación (1, 2, 3, ...). Solo aplica a validadores.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dejar vacío solo para roles globales (por ejemplo, Admin global).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="plants.plant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "unique_together": {("user", "plant", "role", "validation_level")},
            },
        ),
    ]
