# Generated by Django 5.2.7 on 2025-12-15 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="Si esta activo, el usuario debe cambiar su contrasena antes de usar el sistema.",
                    ),
                ),
                (
                    "last_seen_schema_status",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha/hora en la que el usuario vio por ultima vez el estado de esquemas.",
                        null=True,
                    ),
                ),
                (
                    "last_seen_validation_status",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha/hora en la que el usuario vio por ultima vez el estado de sus cargas.",
                        null=True,
                    ),
                ),
                (
                    "last_seen_certification_alert",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha/hora en la que el usuario revisó las alertas de certificación mensual.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LOADER", "Cargador"),
                            ("VALIDATOR", "Validador"),
                            ("VIEWER", "Visualizador"),
                            ("ADMIN", "Administrador"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "validation_level",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nivel de validacion (1, 2, 3, ...). Solo aplica a validadores.",
                        null=True,
                    ),
                ),
                (
                    "can_validate_daily",
                    models.BooleanField(
                        default=False,
                        help_text="Si es validador, puede participar en el flujo diario.",
                    ),
                ),
                (
                    "can_validate_monthly",
                    models.BooleanField(
                        default=False,
                        help_text="Si es validador, puede participar en el flujo mensual/certificacion.",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        choices=[("YLB", "YLB"), ("MHE", "MHE")],
                        default="YLB",
                        help_text="Institucion a la que pertenece este rol (YLB o MHE).",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dejar vacio solo para roles globales (por ejemplo, Admin global).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="plants.plant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "unique_together": {("user", "plant", "role", "validation_level")},
            },
        ),
    ]
