# Generated by Django 5.2.8 on 2026-02-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='viewer_profile_type',
            field=models.CharField(
                choices=[
                    ('STANDARD', 'Visualizador estandar'),
                    ('EXTERNAL_MONTHLY', 'Visualizador externo (mensual)'),
                    ('AUTHORITY_MHE', 'Visualizador autoridad MHE'),
                ],
                default='STANDARD',
                help_text='Define la experiencia de visualizacion para usuarios con rol VIEWER.',
                max_length=30,
            ),
        ),
    ]
