# Generated by Django 5.2.8 on 2025-11-18 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("plants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Dejar vacio solo para roles globales (por ejemplo, Admin global).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="plants.plant",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="validation_level",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nivel de validacion (1, 2, 3, ...). Solo aplica a validadores.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AccountProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="Si esta activo, el usuario debe cambiar su contrasena antes de usar el sistema.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
