# Generated by Codex on 2025-12-18

import django.db.models.deletion
from django.db import migrations, models


def seed_institutions(apps, schema_editor):
    Institution = apps.get_model("accounts", "Institution")
    Membership = apps.get_model("accounts", "Membership")

    defaults = {
        "YLB": "YLB",
        "MHE": "MHE",
    }
    institutions = {}
    for code, name in defaults.items():
        institution, _ = Institution.objects.get_or_create(
            code=code,
            defaults={"name": name, "is_active": True},
        )
        institutions[code] = institution

    for membership in Membership.objects.all():
        code = membership.institution
        if not code:
            continue
        institution = institutions.get(code)
        if institution is None:
            institution, _ = Institution.objects.get_or_create(
                code=code,
                defaults={"name": code, "is_active": True},
            )
            institutions[code] = institution
        membership.institution_ref = institution
        membership.save(update_fields=["institution_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="institution_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="accounts.institution",
            ),
        ),
        migrations.RunPython(seed_institutions, migrations.RunPython.noop),
    ]
