# Generated by Django 5.2.8 on 2026-02-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="Dejar vacio solo para roles globales (por ejemplo, Admin global).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="plants.plant",
            ),
        ),
    ]
