# Generated by Django 5.2.8 on 2025-11-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_membership_plant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="can_validate_daily",
            field=models.BooleanField(
                default=False,
                help_text="Si es validador, puede participar en el flujo diario.",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="can_validate_monthly",
            field=models.BooleanField(
                default=False,
                help_text="Si es validador, puede participar en el flujo mensual/certificacion.",
            ),
        ),
    ]
