# Generated by Django 5.2.8 on 2026-03-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountprofile_viewer_profile_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="last_seen_project_pending",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha/hora en la que el usuario admin reviso la bandeja pendiente de proyectos.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="last_seen_project_status",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha/hora en la que el usuario vio por ultima vez el estado de sus proyectos.",
                null=True,
            ),
        ),
    ]
