# Generated by Django 5.2.8 on 2025-12-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountprofile_last_seen_schema_status"),
        ("accounts", "0002_accountprofile_last_seen_validation_status"),
    ]

    operations = []
