# Generated by Django 5.2.8 on 2026-02-05 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Proyecto asociado (si aplica). Dejar vacio para roles por planta o globales.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plant__isnull", False)),
                fields=("user", "plant", "role", "validation_level"),
                name="uniq_membership_user_plant_role_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("user", "project", "role", "validation_level"),
                name="uniq_membership_user_project_role_level",
            ),
        ),
    ]
