# Generated by Codex on 2025-12-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_institution_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="institution",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="institution_ref",
            new_name="institution",
        ),
        migrations.AlterField(
            model_name="membership",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="accounts.institution",
            ),
        ),
    ]
