# Generated by Django 5.2.8 on 2025-12-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountprofile_last_seen_schema_status"),
        ("accounts", "0003_accountprofile_last_seen_certification_alert"),
    ]

    operations = []
