# Generated by Django 5.2.8 on 2025-11-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_membership_can_validate_daily_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="institution",
            field=models.CharField(
                choices=[("YLB", "YLB"), ("MHE", "MHE")],
                default="YLB",
                help_text="Institucion a la que pertenece este rol (YLB o MHE).",
                max_length=10,
            ),
        ),
    ]
