# Generated by Django 5.2.8 on 2025-12-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_membership_institution_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Institucion a la que pertenece este rol.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="accounts.institution",
            ),
        ),
    ]
