# Generated by Django 5.2.8 on 2026-04-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountprofile_last_seen_project_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='viewer_profile_type',
            field=models.CharField(choices=[('STANDARD', 'Visualizador estandar'), ('EXTERNAL_MONTHLY', 'Visualizador externo (mensual)'), ('AUTHORITY_MHE', 'Visualizador autoridad institucional')], default='STANDARD', help_text='Define la experiencia de visualizacion para usuarios con rol VIEWER.', max_length=30),
        ),
    ]
