# Generated by Django 5.2.7 on 2025-12-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_membership_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="can_validate_weekly",
            field=models.BooleanField(
                default=False,
                help_text="Si es validador, puede participar en el flujo semanal.",
            ),
        ),
    ]
