# Generated by Django 5.2.7 on 2025-12-30 17:40

from django.db import migrations, models


def copy_monthly_to_projections(apps, schema_editor):
    Membership = apps.get_model("accounts", "Membership")
    Membership.objects.filter(
        role="VALIDATOR",
        can_validate_monthly=True,
        can_validate_projections=False,
    ).update(can_validate_projections=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_membership_can_validate_weekly"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="can_validate_projections",
            field=models.BooleanField(
                default=False,
                help_text="Si es validador, puede participar en el flujo de proyecciones (periodicidad no definida).",
            ),
        ),
        migrations.RunPython(copy_monthly_to_projections, migrations.RunPython.noop),
    ]
