# Generated by Django 5.2.7 on 2026-01-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_membership_can_validate_projections"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set(),
        ),
    ]
