# Generated by Django 5.2.7 on 2025-12-15 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "Carga de datos"),
                            ("SUBMIT", "Envío a validación"),
                            ("VALIDATION", "Validación"),
                            ("EDIT", "Corrección de datos"),
                            ("DELETE", "Eliminación de datos"),
                            ("USER", "Gestión de usuarios"),
                            ("SCHEMA", "Gestión de esquemas"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("module", models.CharField(blank=True, max_length=50)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
