# Generated by Django 5.2.8 on 2026-01-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del dataset, por ejemplo 'Producción diaria PICP'.",
                        max_length=255,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "validation_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diaria"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensual"),
                            ("FLEXIBLE", "No definida (proyecciones)"),
                        ],
                        default="DAILY",
                        help_text="Define si este dataset se valida a diario, semanal o como consolidado mensual.",
                        max_length=20,
                    ),
                ),
                (
                    "is_certification",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este esquema es para certificación mensual creada por Administración.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Solo un esquema por familia (planta/proyecto + nombre) deberia estar activo a la vez.",
                    ),
                ),
                (
                    "is_one_time",
                    models.BooleanField(
                        default=False,
                        help_text="Si esta activo, este esquema solo puede cargarse una vez.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("PENDING", "Pendiente aprobación"),
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="DRAFT",
                        help_text="Estado de aprobación del esquema.",
                        max_length=20,
                    ),
                ),
                (
                    "status_comment",
                    models.TextField(
                        blank=True,
                        help_text="Comentario de la última decisión de aprobación/rechazo.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_consolidated_period",
                    models.DateField(
                        blank=True,
                        help_text="Último periodo (último día del mes) consolidado automáticamente para certificación.",
                        null=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Slug legible para URLs, basado en planta, nombre y versión.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_types",
                        to="plants.plant",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_types",
                        to="projects.project",
                    ),
                ),
                (
                    "source_dataset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dataset base diario utilizado para consolidaciones de certificación.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_certifications",
                        to="schemas.datasettype",
                    ),
                ),
            ],
            options={
                "ordering": ["plant__code", "project__name", "name", "-version"],
            },
        ),
        migrations.CreateModel(
            name="ColumnDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre interno del campo (sin espacios). También se usa como encabezado en plantillas y archivos.",
                        max_length=100,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Descripción legible para usuarios (explica qué es la columna y qué datos espera).",
                        max_length=255,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("INTEGER", "Entero"),
                            ("FLOAT", "Decimal"),
                            ("STRING", "Texto"),
                            ("DATE", "Fecha"),
                            ("BOOLEAN", "Booleano"),
                            ("CHOICE", "Categórico"),
                        ],
                        default="FLOAT",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                (
                    "regex",
                    models.CharField(
                        blank=True,
                        help_text="Expresión regular opcional para validar texto.",
                        max_length=255,
                    ),
                ),
                (
                    "choices_raw",
                    models.TextField(
                        blank=True,
                        help_text="Lista de opciones para campos categóricos, una por línea.",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unidad para KPIs y gráficos (t/día, m3, kWh, %...).",
                        max_length=50,
                    ),
                ),
                (
                    "axis_role",
                    models.CharField(
                        choices=[
                            ("NONE", "Ninguno"),
                            ("X", "Eje X"),
                            ("Y", "Eje Y"),
                            ("SERIES", "Serie"),
                            ("FILTER", "Filtro"),
                        ],
                        default="NONE",
                        help_text="Rol principal en gráficos (eje X, Y, serie o filtro).",
                        max_length=10,
                    ),
                ),
                (
                    "default_agg",
                    models.CharField(
                        choices=[
                            ("SUM", "Suma"),
                            ("AVG", "Promedio"),
                            ("MAX", "Máximo"),
                            ("MIN", "Mínimo"),
                            ("COUNT", "Conteo"),
                            ("NONE", "Sin agregación"),
                        ],
                        default="SUM",
                        help_text="Tipo de agregación por defecto para KPIs.",
                        max_length=10,
                    ),
                ),
                (
                    "is_primary_kpi",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el campo es un KPI principal que debería aparecer por defecto.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden sugerido para mostrar en tablas y formularios.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Permite desactivar una columna sin borrar el historial.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="schemas.datasettype",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_type", "display_order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="datasettype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plant__isnull", False)),
                fields=("plant", "name", "version"),
                name="uniq_datasettype_plant_name_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasettype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("project", "name", "version"),
                name="uniq_datasettype_project_name_version",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="columndef",
            unique_together={("dataset_type", "name")},
        ),
    ]
