# Generated by Django 5.2.8 on 2025-11-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del dataset, por ejemplo 'Producción diaria PICP'.",
                        max_length=255,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "validation_frequency",
                    models.CharField(
                        choices=[("DAILY", "Diaria"), ("MONTHLY", "Mensual")],
                        default="DAILY",
                        help_text="Define si este dataset se valida a diario o como consolidado mensual.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Solo un esquema por familia (planta+nombre) debería estar activo a la vez.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_types",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["plant__code", "name", "-version"],
                "unique_together": {("plant", "name", "version")},
            },
        ),
        migrations.CreateModel(
            name="ColumnDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre interno del campo (sin espacios).",
                        max_length=100,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nombre legible para usuarios.", max_length=255
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("INTEGER", "Entero"),
                            ("FLOAT", "Decimal"),
                            ("STRING", "Texto"),
                            ("DATE", "Fecha"),
                            ("BOOLEAN", "Booleano"),
                            ("CHOICE", "Categórico"),
                        ],
                        default="FLOAT",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                (
                    "regex",
                    models.CharField(
                        blank=True,
                        help_text="Expresión regular opcional para validar texto.",
                        max_length=255,
                    ),
                ),
                (
                    "choices_raw",
                    models.TextField(
                        blank=True,
                        help_text="Lista de opciones para campos categóricos, una por línea.",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unidad para KPIs y gráficos (t/día, m³, kWh, %...).",
                        max_length=50,
                    ),
                ),
                (
                    "axis_role",
                    models.CharField(
                        choices=[
                            ("NONE", "Ninguno"),
                            ("X", "Eje X"),
                            ("Y", "Eje Y"),
                            ("SERIES", "Serie"),
                            ("FILTER", "Filtro"),
                        ],
                        default="NONE",
                        help_text="Rol principal en gráficos (eje X, Y, serie o filtro).",
                        max_length=10,
                    ),
                ),
                (
                    "default_agg",
                    models.CharField(
                        choices=[
                            ("SUM", "Suma"),
                            ("AVG", "Promedio"),
                            ("MAX", "Máximo"),
                            ("MIN", "Mínimo"),
                            ("COUNT", "Conteo"),
                            ("NONE", "Sin agregación"),
                        ],
                        default="SUM",
                        help_text="Tipo de agregación por defecto para KPIs.",
                        max_length=10,
                    ),
                ),
                (
                    "is_primary_kpi",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el campo es un KPI principal que debería aparecer por defecto.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden sugerido para mostrar en tablas y formularios.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Permite desactivar una columna sin borrar el historial.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="schemas.datasettype",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_type", "display_order", "name"],
                "unique_together": {("dataset_type", "name")},
            },
        ),
    ]
