# Generated by Django 5.2.7 on 2025-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="columndef",
            name="label",
            field=models.CharField(
                help_text="Descripción legible para usuarios (explica qué es la columna y qué datos espera).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="name",
            field=models.CharField(
                help_text="Nombre interno del campo (sin espacios). También se usa como encabezado en plantillas y archivos.",
                max_length=100,
            ),
        ),
    ]
