# Generated by Django 5.2.7 on 2025-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasettype",
            name="is_certification",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este esquema es para certificaci��n mensual creada por Administraci��n.",
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="axis_role",
            field=models.CharField(
                choices=[
                    ("NONE", "Ninguno"),
                    ("X", "Eje X"),
                    ("Y", "Eje Y"),
                    ("SERIES", "Serie"),
                    ("FILTER", "Filtro"),
                ],
                default="NONE",
                help_text="Rol principal en grǭficos (eje X, Y, serie o filtro).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="choices_raw",
            field=models.TextField(
                blank=True,
                help_text="Lista de opciones para campos categ��ricos, una por l��nea.",
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Entero"),
                    ("FLOAT", "Decimal"),
                    ("STRING", "Texto"),
                    ("DATE", "Fecha"),
                    ("BOOLEAN", "Booleano"),
                    ("CHOICE", "Categ��rico"),
                ],
                default="FLOAT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="default_agg",
            field=models.CharField(
                choices=[
                    ("SUM", "Suma"),
                    ("AVG", "Promedio"),
                    ("MAX", "Mǭximo"),
                    ("MIN", "M��nimo"),
                    ("COUNT", "Conteo"),
                    ("NONE", "Sin agregaci��n"),
                ],
                default="SUM",
                help_text="Tipo de agregaci��n por defecto para KPIs.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="is_primary_kpi",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el campo es un KPI principal que deber��a aparecer por defecto.",
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="regex",
            field=models.CharField(
                blank=True,
                help_text="Expresi��n regular opcional para validar texto.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="Unidad para KPIs y grǭficos (t/d��a, m��, kWh, %...).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="datasettype",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Solo un esquema por familia (planta+nombre) deber��a estar activo a la vez.",
            ),
        ),
        migrations.AlterField(
            model_name="datasettype",
            name="name",
            field=models.CharField(
                help_text="Nombre del dataset, por ejemplo 'Producci��n diaria PICP'.",
                max_length=255,
            ),
        ),
    ]
