# Generated by Django 5.2.7 on 2025-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0002_datasettype_is_certification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasettype",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("PENDING", "Pendiente aprobación"),
                    ("APPROVED", "Aprobado"),
                ],
                default="DRAFT",
                help_text="Estado de aprobación del esquema.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="axis_role",
            field=models.CharField(
                choices=[
                    ("NONE", "Ninguno"),
                    ("X", "Eje X"),
                    ("Y", "Eje Y"),
                    ("SERIES", "Serie"),
                    ("FILTER", "Filtro"),
                ],
                default="NONE",
                help_text="Rol principal en gráficos (eje X, Y, serie o filtro).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="choices_raw",
            field=models.TextField(
                blank=True,
                help_text="Lista de opciones para campos categóricos, una por línea.",
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("INTEGER", "Entero"),
                    ("FLOAT", "Decimal"),
                    ("STRING", "Texto"),
                    ("DATE", "Fecha"),
                    ("BOOLEAN", "Booleano"),
                    ("CHOICE", "Categórico"),
                ],
                default="FLOAT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="default_agg",
            field=models.CharField(
                choices=[
                    ("SUM", "Suma"),
                    ("AVG", "Promedio"),
                    ("MAX", "Máximo"),
                    ("MIN", "Mínimo"),
                    ("COUNT", "Conteo"),
                    ("NONE", "Sin agregación"),
                ],
                default="SUM",
                help_text="Tipo de agregación por defecto para KPIs.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="is_primary_kpi",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el campo es un KPI principal que debería aparecer por defecto.",
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="regex",
            field=models.CharField(
                blank=True,
                help_text="Expresión regular opcional para validar texto.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="columndef",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="Unidad para KPIs y gráficos (t/día, m3, kWh, %...).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="datasettype",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Solo un esquema por familia (planta+nombre) deberia estar activo a la vez.",
            ),
        ),
        migrations.AlterField(
            model_name="datasettype",
            name="is_certification",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este esquema es para certificación mensual creada por Administración.",
            ),
        ),
        migrations.AlterField(
            model_name="datasettype",
            name="name",
            field=models.CharField(
                help_text="Nombre del dataset, por ejemplo 'Producción diaria PICP'.",
                max_length=255,
            ),
        ),
    ]
