# Generated by Django 5.2.8 on 2026-04-24 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_datasettype_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasettype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Solo un esquema por familia (entidad/proyecto + nombre) deberia estar activo a la vez.'),
        ),
        migrations.AlterField(
            model_name='datasettype',
            name='name',
            field=models.CharField(help_text="Nombre del conjunto, por ejemplo 'Atenciones mensuales en Medicina Nuclear'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='datasettype',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug legible para URLs, basado en entidad, nombre y versión.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='datasettype',
            name='source_dataset',
            field=models.ForeignKey(blank=True, help_text='Conjunto base diario utilizado para consolidaciones de certificación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_certifications', to='schemas.datasettype'),
        ),
        migrations.AlterField(
            model_name='datasettype',
            name='validation_frequency',
            field=models.CharField(choices=[('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('FLEXIBLE', 'No definida (proyecciones)')], default='DAILY', help_text='Define si este conjunto se valida a diario, semanal o como consolidado mensual.', max_length=20),
        ),
    ]
