# Generated by Django 5.2.7 on 2025-12-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0003_alter_datasettype_validation_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasettype",
            name="validation_frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "Diaria"),
                    ("WEEKLY", "Semanal"),
                    ("MONTHLY", "Mensual"),
                    ("FLEXIBLE", "No definida (proyecciones)"),
                ],
                default="DAILY",
                help_text="Define si este dataset se valida a diario, semanal o como consolidado mensual.",
                max_length=20,
            ),
        ),
    ]
