# Generated by Django 5.2.7 on 2025-11-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0003_datasettype_status_alter_columndef_axis_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasettype",
            name="status_comment",
            field=models.TextField(
                blank=True,
                help_text="Comentario de la última decisión de aprobación/rechazo.",
            ),
        ),
        migrations.AlterField(
            model_name="datasettype",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("PENDING", "Pendiente aprobación"),
                    ("APPROVED", "Aprobado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="DRAFT",
                help_text="Estado de aprobación del esquema.",
                max_length=20,
            ),
        ),
    ]
