# Generated by Django 5.2.7 on 2026-01-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0001_initial"),
        ("projects", "0001_initial"),
        ("schemas", "0004_alter_datasettype_validation_frequency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasettype",
            options={"ordering": ["plant__code", "project__name", "name", "-version"]},
        ),
        migrations.AlterUniqueTogether(
            name="datasettype",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="datasettype",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_types",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="datasettype",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Solo un esquema por familia (planta/proyecto + nombre) deberia estar activo a la vez.",
            ),
        ),
        migrations.AlterField(
            model_name="datasettype",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_types",
                to="plants.plant",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasettype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plant__isnull", False)),
                fields=("plant", "name", "version"),
                name="uniq_datasettype_plant_name_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasettype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("project", "name", "version"),
                name="uniq_datasettype_project_name_version",
            ),
        ),
    ]
