# Generated by Django 5.2.7 on 2025-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0004_datasettype_status_comment_alter_datasettype_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasettype",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Slug legible para URLs, basado en planta, nombre y versión.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
