# Generated by Django 5.2.7 on 2026-01-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0005_alter_datasettype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasettype",
            name="is_one_time",
            field=models.BooleanField(
                default=False,
                help_text="Si esta activo, este esquema solo puede cargarse una vez.",
            ),
        ),
    ]
