# Generated by Django 5.2.8 on 2026-02-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structure", "0002_entitytype_entity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entitytype",
            name="legacy_target",
        ),
    ]
